name: flutter_boilerplate
description: Boilerplate for new flutter projects.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  either_dart: ^1.0.0
  auto_route: ^7.7.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  cupertino_icons: ^1.0.2
  riverpod_annotation: ^2.3.3
  json_annotation: ^4.8.1
  dio: ^5.3.4
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  auto_route_generator:

flutter:
  uses-material-design: true

